"""Retouch Recipe System configuration.

Maps high-level recipe names to float/int ratios.
"""

RECIPES = {
    "natural": {
        "frequency": {"smooth": 0.30},
        "skin": {"equalize": 0.20, "rosy": 0.10},
        "eyes": {"whites": 0.05, "iris": 0.05, "catchlight": 0.05},
        "lips": {"tint": None, "gloss": 0.05},
        "hair": {"shine": 0.05},
        "dodge_burn": {"amount": 0.00},
        "color_harmony": {"preset": "natural", "amount": 0.00},
        "bloom": {"opacity": 0.00},
        "texture": {"opacity": 1.00},
    },
    "portrait": {
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.35, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.15, "catchlight": 0.15},
        "lips": {"tint": None, "gloss": 0.10},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.60},
        "bloom": {"opacity": 0.03},
        "texture": {"opacity": 1.00},
    },
    "cosplay": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.40, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "cosplay_3d": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "cosplay_no_eq": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "xiaohongshu": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.40, "rosy": 0.50},
        "eyes": {"whites": 0.25, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": "rose", "gloss": 0.20},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "dreamy", "amount": 0.35},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "anime": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.30, "rosy": 0.30},
        "eyes": {"whites": 0.40, "iris": 0.50, "catchlight": 0.40},
        "lips": {"tint": "coral", "gloss": 0.25},
        "hair": {"shine": 0.40},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "anime", "amount": 0.30},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "beauty": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.30, "rosy": 0.25},
        "eyes": {"whites": 0.20, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": None, "gloss": 0.30},
        "hair": {"shine": 0.20},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "beauty", "amount": 0.65},
        "bloom": {"opacity": 0.10},
        "texture": {"opacity": 0.85},
    },
    "dreamy": {
        "frequency": {"smooth": 0.60},
        "skin": {"equalize": 0.35, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.30, "catchlight": 0.25},
        "lips": {"tint": "rose", "gloss": 0.30},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "dreamy", "amount": 0.80},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "magazine": {
        "frequency": {"smooth": 0.70},
        "skin": {"equalize": 0.35, "rosy": 0.60},
        "eyes": {"whites": 0.20, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": None, "gloss": 0.15},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.25},
        "color_harmony": {"preset": "magazine", "amount": 0.70},
        "bloom": {"opacity": 0.03},
        "texture": {"opacity": 0.85},
    },
    "korean_beauty": {
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.10, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "pink", "gloss": 0.15},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.30},
        "bloom": {"opacity": 0.04},
        "texture": {"opacity": 0.95},
    },
    "idol": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.30},
        "eyes": {"whites": 0.25, "iris": 0.35, "catchlight": 0.30},
        "lips": {"tint": "rose", "gloss": 0.25},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.20},
        "color_harmony": {"preset": "cosplay", "amount": 0.40},
        "bloom": {"opacity": 0.07},
        "texture": {"opacity": 0.90},
    },
    "wedding": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.25},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "rose", "gloss": 0.10},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "beauty", "amount": 0.50},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.90},
    },
    "anime_cosplay": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "scifi_cosplay": {
        # Tuned to match the vibrant, ultra-smooth, high-contrast, porcelain-skin reference.
        # Features strong highlights, clean shadows, strong eye catchlights, and ethereal bloom.
        "frequency": {"smooth": 0.85, "mid_reduction": 0.75}, # high smoothing + strong blemish reduction for doll skin
        "skin": {"equalize": 0.20, "rosy": 0.45},  # increase whitening & equalization for bright even skin
        "eyes": {"whites": 0.35, "iris": 0.55, "catchlight": 0.50},  # punchy colored contacts and catchlights
        "lips": {"tint": "cosplay", "gloss": 0.45},  # vibrant lips with strong glossy highlights
        "hair": {"shine": 0.40},              # structural shine on wig
        "dodge_burn": {"amount": 0.35},       # stronger facial sculpting / nose highlight
        "color_harmony": {"preset": "scifi", "amount": 0.70},  # custom sci-fi cyan/pink split toning & S-curve
        "bloom": {"opacity": 0.15},           # strong ethereal neon bloom/glow
        "texture": {"opacity": 0.25},         # heavily reduce texture to 25% for a clean porcelain digital look
    },
    "fantasy_goddess": {
        # Ethereal low-contrast fantasy look with soft-focus glow, atmospheric fog, and sparkles.
        "frequency": {"smooth": 0.75, "mid_reduction": 0.60},
        "skin": {"equalize": 0.20, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.40, "catchlight": 0.35},
        "lips": {"tint": "pink", "gloss": 0.30},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "fantasy", "amount": 0.80},
        "bloom": {"opacity": 0.45},
        "texture": {"opacity": 0.25},
        "contrast": -25,
    },
    "cyber_doll": {
        # Stronger cosplay reference look: porcelain skin, bright eyes, pink/cyan lighting, and punchy output.
        "frequency": {"smooth": 0.82, "mid_reduction": 0.70},
        "skin": {"equalize": 0.12, "rosy": 0.42},
        "eyes": {"whites": 0.36, "iris": 0.60, "catchlight": 0.55},
        "lips": {"tint": "cosplay", "gloss": 0.48},
        "hair": {"shine": 0.55},
        "dodge_burn": {"amount": 0.34},
        "color_harmony": {"preset": "cyber_doll", "amount": 0.90},
        "bloom": {"opacity": 0.16},
        "texture": {"opacity": 0.30},
        "finish": {"impact": 0.70},
    },
    "pink_dream": {
        "frequency": {"smooth": 0.25, "mid_reduction": 0.35},
        "skin": {"equalize": 0.30, "rosy": 0.45},
        "eyes": {"whites": 0.35, "iris": 0.50, "catchlight": 0.45},
        "lips": {"tint": None, "gloss": 0.00},
        "hair": {"shine": 0.50},
        "dodge_burn": {"amount": 0.30},
        "color_harmony": {"preset": "pink_dream", "amount": 0.85},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.90},
        "finish": {"impact": 0.60},
    },
    "blue_dream": {
        "frequency": {"smooth": 0.75, "mid_reduction": 0.60},
        "skin": {"equalize": 0.20, "rosy": 0.30},
        "eyes": {"whites": 0.30, "iris": 0.40, "catchlight": 0.35},
        "lips": {"tint": "cosplay", "gloss": 0.30},
        "hair": {"shine": 0.35},
        "dodge_burn": {"amount": 0.20},
        "color_harmony": {"preset": "blue_dream", "amount": 0.80},
        "bloom": {"opacity": 0.20},
        "texture": {"opacity": 0.35},
        "finish": {"impact": 0.50},
    },
    "xhs_ultrasoft": {
        "frequency": {"smooth": 0.85, "mid_reduction": 0.75},
        "skin": {"equalize": 0.30, "rosy": 0.50},
        "eyes": {"whites": 0.25, "iris": 0.30, "catchlight": 0.25},
        "lips": {"tint": "rose", "gloss": 0.25},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "xhs_ultrasoft", "amount": 0.90},
        "bloom": {"opacity": 0.15},
        "texture": {"opacity": 0.20},
        "finish": {"impact": 0.40},
    },
    "meitu_clone": {
        "frequency": {"smooth": 0.70, "mid_reduction": 0.60},
        "skin": {"equalize": 0.25, "rosy": 0.45},
        "eyes": {"whites": 0.38, "iris": 0.60, "catchlight": 0.50},
        "lips": {"tint": None, "gloss": 0.00},
        "hair": {"shine": 0.50},
        "dodge_burn": {"amount": 0.35},
        "color_harmony": {"preset": "meitu_clone", "amount": 0.90},
        "bloom": {"opacity": 0.16},
        "texture": {"opacity": 0.45},
        "finish": {"impact": 0.70},
    },
    "fuji_porcelain": {
        "frequency": {"smooth": 0.72, "mid_reduction": 0.75},
        "skin": {"equalize": 0.50, "rosy": 0.70},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.30},
        "lips": {"tint": "pink", "gloss": 0.20},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.55},
        "color_harmony": {"preset": "natural", "amount": 0.50},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.35},
        "specular_bloom": 50,
    },

    # ------------------------------------------------------------------
    # Anime Cinematic Series — AAA game promotional art look
    # All numeric values mapped to engine recipe format (0-1 ratios where
    # the engine multiplies by 100, or raw values for flat params).
    # ------------------------------------------------------------------
    "anime_cinematic_v1": {
        "extends": "natural",

        "frequency": {"smooth": 0.32, "mid_reduction": 0.22},
        "skin": {"equalize": 0.38, "porcelain": 0.42},
        "eyes": {"whites": 0.18, "iris": 0.22, "catchlight": 0.25, "dark_circles": 0.22},
        "lips": {"tint": None, "gloss": 0.22},
        "hair": {"shine": 0.75},
        "dodge_burn": 18.0,
        "texture": {"opacity": 0.88},

        # Flat top-level keys (already wired in build_context)
        "relight_strength": 35.0,
        "light_azimuth": 45.0,
        "light_elevation": 35.0,

        "brightness": 6.0,
        "contrast": 12.0,
        "highlights": -10.0,
        "shadows": -4.0,
        "whites": 8.0,
        "blacks": 6.0,
        "clarity": 14.0,
        "saturation": 6.0,
        "vibrance": 12.0,

        "shadow_hue": 225.0,
        "shadow_sat": 12.0,
        "midtone_hue": 0.0,
        "midtone_sat": 0.0,
        "highlight_hue": 320.0,
        "highlight_sat": 10.0,

        "bloom": {"opacity": 0.16, "threshold": 190.0},
        "glow": 8.0,

        "vignette": 6.0,
        "sharpen": 20.0,
        "sharpen_radius": 1.2,
        "chromatic_aberration": 4.0,
        "grain": 0.0,
        "specular_bloom_tone": "rosy",
    },

    "anime_cinematic_soft": {
        "extends": "anime_cinematic_v1",
        "contrast": 8.0,
        "skin": {"porcelain": 0.50},
        "bloom": {"opacity": 0.22},
        "highlight_sat": 6.0,
        "clarity": 8.0,
        "chromatic_aberration": 2.0,
        "hair": {"shine": 0.85},
    },

    "anime_cinematic_action": {
        "extends": "anime_cinematic_v1",
        "contrast": 18.0,
        "clarity": 24.0,
        "sharpen": 30.0,
        "relight_strength": 45.0,
        "chromatic_aberration": 6.0,
        "bloom": {"opacity": 0.10},
        "vignette": 10.0,
    },

    "anime_cinematic_fantasy": {
        "extends": "anime_cinematic_v1",
        "brightness": 10.0,
        "bloom": {"opacity": 0.25},
        "glow": 18.0,
        "skin": {"porcelain": 0.55},
        "hair": {"shine": 0.90},
        "highlight_sat": 14.0,
        "shadow_sat": 14.0,
        "chromatic_aberration": 5.0,
    },
}
