"""Retouch Recipe System configuration.

Maps high-level recipe names to float/int ratios.
"""

RECIPES = {
    "natural": {
        "frequency": {"smooth": 0.30},
        "skin": {"equalize": 0.20, "rosy": 0.10},
        "eyes": {"whites": 0.05, "iris": 0.05, "catchlight": 0.05},
        "lips": {"tint": None, "gloss": 0.05},
        "hair": {"shine": 0.05},
        "dodge_burn": {"amount": 0.00},
        "color_harmony": {"preset": "natural", "amount": 0.00},
        "bloom": {"opacity": 0.00},
        "texture": {"opacity": 1.00},
    },
    "portrait": {
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.35, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.15, "catchlight": 0.15},
        "lips": {"tint": None, "gloss": 0.10},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.60},
        "bloom": {"opacity": 0.03},
        "texture": {"opacity": 1.00},
    },
    "cosplay": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.40, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "cosplay_3d": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "cosplay_no_eq": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "xiaohongshu": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.40, "rosy": 0.50},
        "eyes": {"whites": 0.25, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": "rose", "gloss": 0.20},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "dreamy", "amount": 0.35},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "anime": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.30, "rosy": 0.30},
        "eyes": {"whites": 0.40, "iris": 0.50, "catchlight": 0.40},
        "lips": {"tint": "coral", "gloss": 0.25},
        "hair": {"shine": 0.40},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "anime", "amount": 0.30},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "beauty": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.30, "rosy": 0.25},
        "eyes": {"whites": 0.20, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": None, "gloss": 0.30},
        "hair": {"shine": 0.20},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "beauty", "amount": 0.65},
        "bloom": {"opacity": 0.10},
        "texture": {"opacity": 0.85},
    },
    "dreamy": {
        "frequency": {"smooth": 0.60},
        "skin": {"equalize": 0.35, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.30, "catchlight": 0.25},
        "lips": {"tint": "rose", "gloss": 0.30},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "dreamy", "amount": 0.80},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
    },
    "magazine": {
        "frequency": {"smooth": 0.70},
        "skin": {"equalize": 0.35, "rosy": 0.60},
        "eyes": {"whites": 0.20, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": None, "gloss": 0.15},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.25},
        "color_harmony": {"preset": "magazine", "amount": 0.70},
        "bloom": {"opacity": 0.03},
        "texture": {"opacity": 0.85},
    },
    "korean_beauty": {
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.10, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "pink", "gloss": 0.15},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.30},
        "bloom": {"opacity": 0.04},
        "texture": {"opacity": 0.95},
    },
    "idol": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.30},
        "eyes": {"whites": 0.25, "iris": 0.35, "catchlight": 0.30},
        "lips": {"tint": "rose", "gloss": 0.25},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.20},
        "color_harmony": {"preset": "cosplay", "amount": 0.40},
        "bloom": {"opacity": 0.07},
        "texture": {"opacity": 0.90},
    },
    "wedding": {
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.25},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "rose", "gloss": 0.10},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "beauty", "amount": 0.50},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.90},
    },
    "anime_cosplay": {
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
}
