"""Retouch Recipe System configuration.

Maps high-level recipe names to float/int ratios.
"""

RECIPES = {
    "natural": {
        "frequency": {"smooth": 0.30},
        "skin": {"equalize": 0.20, "rosy": 0.10},
        "eyes": {"whites": 0.05, "iris": 0.05, "catchlight": 0.05},
        "lips": {"tint": None, "gloss": 0.05},
        "hair": {"shine": 0.05},
        "dodge_burn": {"amount": 0.00},
        "color_harmony": {"preset": "natural", "amount": 0.00},
        "bloom": {"opacity": 0.00},
        "texture": {"opacity": 1.00},
        
        # Modular mappings
        "slimming": 0.0,
        "blush": 0.0,
        "lip_finish": "gloss",
        "nose_blush": False,
        "under_eye_blush": False,
        "white_costume_lift": False,
    },
    "portrait": {
        "extends": "natural",
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.35, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.15, "catchlight": 0.15},
        "lips": {"tint": None, "gloss": 0.10},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.60},
        "bloom": {"opacity": 0.03},
        "texture": {"opacity": 1.00},
    },
    "cosplay": {
        "extends": "natural",
        "frequency": {"smooth": 0.55},
        "skin": {"equalize": 0.40, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 25.0,
        "nose_blush": True,
        "under_eye_blush": True,
    },
    "cosplay_3d": {
        "extends": "cosplay",
        "skin": {"equalize": 0.00, "rosy": 0.35},
    },
    "cosplay_no_eq": {
        "extends": "cosplay",
        "skin": {"equalize": 0.00, "rosy": 0.35},
    },
    "xiaohongshu": {
        "extends": "natural",
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.40, "rosy": 0.50},
        "eyes": {"whites": 0.25, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": "rose", "gloss": 0.20},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "fantasy", "amount": 0.35},
        "bloom": {"opacity": 0.08},
        "texture": {"opacity": 0.90},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 25.0,
    },
    "beauty": {
        "extends": "natural",
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.30, "rosy": 0.25},
        "eyes": {"whites": 0.20, "iris": 0.25, "catchlight": 0.20},
        "lips": {"tint": None, "gloss": 0.30},
        "hair": {"shine": 0.20},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "beauty", "amount": 0.65},
        "bloom": {"opacity": 0.10},
        "texture": {"opacity": 0.85},
    },
    "korean_beauty": {
        "extends": "natural",
        "frequency": {"smooth": 0.45},
        "skin": {"equalize": 0.10, "rosy": 0.20},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "pink", "gloss": 0.15},
        "hair": {"shine": 0.10},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "natural", "amount": 0.30},
        "bloom": {"opacity": 0.04},
        "texture": {"opacity": 0.95},
        
        # Modular overrides
        "lip_finish": "velvet",
    },
    "idol": {
        "extends": "natural",
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.30},
        "eyes": {"whites": 0.25, "iris": 0.35, "catchlight": 0.30},
        "lips": {"tint": "rose", "gloss": 0.25},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.20},
        "color_harmony": {"preset": "cosplay", "amount": 0.40},
        "bloom": {"opacity": 0.07},
        "texture": {"opacity": 0.90},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 25.0,
    },
    "wedding": {
        "extends": "natural",
        "frequency": {"smooth": 0.50},
        "skin": {"equalize": 0.15, "rosy": 0.25},
        "eyes": {"whites": 0.15, "iris": 0.20, "catchlight": 0.15},
        "lips": {"tint": "rose", "gloss": 0.10},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.10},
        "color_harmony": {"preset": "beauty", "amount": 0.50},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.90},
        
        # Modular overrides
        "blush": 25.0,
        "lip_finish": "matte",
    },
    "anime_cosplay": {
        "extends": "cosplay",
        "skin": {"equalize": 0.00, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.25},
        "lips": {"tint": "cosplay", "gloss": 0.20},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "cosplay", "amount": 0.20},
        "bloom": {"opacity": 0.06},
        "texture": {"opacity": 0.90},
    },
    "scifi_cosplay": {
        "extends": "natural",
        "frequency": {"smooth": 0.85, "mid_reduction": 0.75},
        "skin": {"equalize": 0.20, "rosy": 0.45},
        "eyes": {"whites": 0.35, "iris": 0.55, "catchlight": 0.50},
        "lips": {"tint": "cosplay", "gloss": 0.45},
        "hair": {"shine": 0.40},
        "dodge_burn": {"amount": 0.35},
        "color_harmony": {"preset": "cyberpunk", "amount": 0.70},
        "bloom": {"opacity": 0.15},
        "texture": {"opacity": 0.25},
        
        # Modular overrides
        "slimming": 0.0,
        "blush": 35.0,
        "nose_blush": True,
        "under_eye_blush": True,
    },
    "fantasy_goddess": {
        "extends": "natural",
        "frequency": {"smooth": 0.75, "mid_reduction": 0.60},
        "skin": {"equalize": 0.20, "rosy": 0.35},
        "eyes": {"whites": 0.30, "iris": 0.40, "catchlight": 0.35},
        "lips": {"tint": "pink", "gloss": 0.30},
        "hair": {"shine": 0.30},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "fantasy", "amount": 0.80},
        "bloom": {"opacity": 0.45},
        "texture": {"opacity": 0.25},
        "contrast": -25,
        
        # Modular overrides
        "slimming": 35.0,
        "blush": 30.0,
        "nose_blush": True,
        "under_eye_blush": True,
    },
    "pink_dream": {
        "extends": "natural",
        "frequency": {"smooth": 0.25, "mid_reduction": 0.35},
        "skin": {"equalize": 0.30, "rosy": 0.45},
        "eyes": {"whites": 0.35, "iris": 0.50, "catchlight": 0.45},
        "lips": {"tint": None, "gloss": 0.00},
        "hair": {"shine": 0.50},
        "dodge_burn": {"amount": 0.30},
        "color_harmony": {"preset": "pink_dream", "amount": 0.85},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.90},
        "finish": {"impact": 0.60},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 30.0,
        "nose_blush": True,
        "under_eye_blush": True,
        "white_costume_lift": True,
    },
    "blue_dream": {
        "extends": "natural",
        "frequency": {"smooth": 0.75, "mid_reduction": 0.60},
        "skin": {"equalize": 0.20, "rosy": 0.30},
        "eyes": {"whites": 0.30, "iris": 0.40, "catchlight": 0.35},
        "lips": {"tint": "cosplay", "gloss": 0.30},
        "hair": {"shine": 0.35},
        "dodge_burn": {"amount": 0.20},
        "color_harmony": {"preset": "blue_dream", "amount": 0.80},
        "bloom": {"opacity": 0.20},
        "texture": {"opacity": 0.35},
        "finish": {"impact": 0.50},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 25.0,
    },
    "xhs_ultrasoft": {
        "extends": "natural",
        "frequency": {"smooth": 0.85, "mid_reduction": 0.75},
        "skin": {"equalize": 0.30, "rosy": 0.50},
        "eyes": {"whites": 0.25, "iris": 0.30, "catchlight": 0.25},
        "lips": {"tint": "rose", "gloss": 0.25},
        "hair": {"shine": 0.25},
        "dodge_burn": {"amount": 0.15},
        "color_harmony": {"preset": "xhs_ultrasoft", "amount": 0.90},
        "bloom": {"opacity": 0.15},
        "texture": {"opacity": 0.20},
        "finish": {"impact": 0.40},
        
        # Modular overrides
        "slimming": 30.0,
        "blush": 25.0,
        "lip_finish": "velvet",
    },
    "fuji_porcelain": {
        "extends": "natural",
        "frequency": {"smooth": 0.72, "mid_reduction": 0.75},
        "skin": {"equalize": 0.50, "rosy": 0.70},
        "eyes": {"whites": 0.30, "iris": 0.35, "catchlight": 0.30},
        "lips": {"tint": "pink", "gloss": 0.20},
        "hair": {"shine": 0.15},
        "dodge_burn": {"amount": 0.55},
        "color_harmony": {"preset": "natural", "amount": 0.50},
        "bloom": {"opacity": 0.05},
        "texture": {"opacity": 0.35},
        "specular_bloom": 50,
    },
    "anime_cinematic_v1": {
        "extends": "natural",
        "frequency": {"smooth": 0.32, "mid_reduction": 0.22},
        "skin": {"equalize": 0.38, "porcelain": 0.42},
        "eyes": {"whites": 0.18, "iris": 0.22, "catchlight": 0.25, "dark_circles": 0.22},
        "lips": {"tint": None, "gloss": 0.22},
        "hair": {"shine": 0.75},
        "dodge_burn": 18.0,
        "texture": {"opacity": 0.88},
        "relight_strength": 35.0,
        "light_azimuth": 45.0,
        "light_elevation": 35.0,
        "brightness": 6.0,
        "contrast": 12.0,
        "highlights": -10.0,
        "shadows": -4.0,
        "whites": 8.0,
        "blacks": 6.0,
        "clarity": 14.0,
        "saturation": 6.0,
        "vibrance": 12.0,
        "shadow_hue": 225.0,
        "shadow_sat": 12.0,
        "midtone_hue": 0.0,
        "midtone_sat": 0.0,
        "highlight_hue": 320.0,
        "highlight_sat": 10.0,
        "bloom": {"opacity": 0.16, "threshold": 190.0},
        "glow": 8.0,
        "vignette": 6.0,
        "sharpen": 20.0,
        "sharpen_radius": 1.2,
        "chromatic_aberration": 4.0,
        "grain": 0.0,
        "specular_bloom_tone": "rosy",
        
        # Modular overrides
        "blush": 30.0,
        "nose_blush": True,
        "under_eye_blush": True,
        "white_costume_lift": True,
    },
    "anime_cinematic_soft": {
        "extends": "anime_cinematic_v1",
        "contrast": 8.0,
        "skin": {"porcelain": 0.50},
        "bloom": {"opacity": 0.22},
        "highlight_sat": 6.0,
        "clarity": 8.0,
        "chromatic_aberration": 2.0,
        "hair": {"shine": 0.85},
    },
    "anime_cinematic_action": {
        "extends": "anime_cinematic_v1",
        "contrast": 18.0,
        "clarity": 24.0,
        "sharpen": 30.0,
        "relight_strength": 45.0,
        "chromatic_aberration": 6.0,
        "bloom": {"opacity": 0.10},
        "vignette": 10.0,
    },
    "anime_crystal_void": {
        "extends": "anime_cinematic_v1",
        "subject_separation": 0.85,
        "bloom": {"opacity": 0.35},
        "chromatic_aberration": 1.5,
        "eyes": {"iris": 0.20},
        "background_blur": 0.55,
        "background_desaturation": 0.40,
        "light_wrap": 0.25,
        "blue_shadow_grade": 0.75,
        "cyan_midtone_grade": 0.45,
        "subject_sharpen": 0.30,
        "matte_black": 0.10,
    },
    "anime_cinematic_fantasy": {
        "extends": "anime_cinematic_v1",
        "brightness": 10.0,
        "bloom": {"opacity": 0.25},
        "glow": 18.0,
        "skin": {"porcelain": 0.55},
        "hair": {"shine": 0.90},
        "highlight_sat": 14.0,
        "shadow_sat": 14.0,
        "chromatic_aberration": 5.0,
    },
}

RECIPES["soft"] = RECIPES["anime_cinematic_soft"]
RECIPES["action"] = RECIPES["anime_cinematic_action"]
RECIPES["fantasy"] = RECIPES["anime_cinematic_fantasy"]
